export const MESSAGE_LIMITS = {
  MESSAGE_MAX_LENGTH: 1024,
  TITLE_MAX_LENGTH: 250,
  URL_MAX_LENGTH: 512,
  URL_TITLE_MAX_LENGTH: 100,
  RETRY_MIN_SECONDS: 30,
  EXPIRE_MAX_SECONDS: 10800,
} as const

export const EMERGENCY_DEFAULTS = {
  RETRY_SECONDS: 60,
  EXPIRE_SECONDS: 3600,
} as const
