export const PushoverSound = {
  PUSHOVER: 'pushover',
  BIKE: 'bike',
  BUGLE: 'bugle',
  CASH_REGISTER: 'cashregister',
  CLASSICAL: 'classical',
  COSMIC: 'cosmic',
  FALLING: 'falling',
  GAMELAN: 'gamelan',
  INCOMING: 'incoming',
  INTERMISSION: 'intermission',
  MAGIC: 'magic',
  MECHANICAL: 'mechanical',
  PIANO_BAR: 'pianobar',
  SIREN: 'siren',
  SPACE_ALARM: 'spacealarm',
  TUG_BOAT: 'tugboat',
  ALIEN: 'alien',
  CLIMB: 'climb',
  PERSISTENT: 'persistent',
  ECHO: 'echo',
  UP_DOWN: 'updown',
  VIBRATE: 'vibrate',
  NONE: 'none',
} as const
